package(default_visibility = ["//visibility:public"])

load("//protobuf:rules.bzl", "proto_language")

proto_language(
    name = "objc",
    output_file_style = "capitalize",
    pb_file_extensions = [
        ".pbobjc.h",
        ".pbobjc.m",
    ],
)
